### ISSUE TITLE
Celery container unable to find dandi.celery module

### ISSUE THREAD

**Issue by jwodder** [dandi/dandi-publish#120]
For dandi/dandi-cli#164, I'm trying to rework dandi/dandi-publish#71 into a viable Docker Compose setup; my current attempt is [here](https://github.com/dandi/dandi-cli/tree/gh-164/publish-docker).  Currently, once all the containers are brought up, the celery container exits with code 1; its logs are:

```
Error: 
Unable to load celery application.
The module dandi.celery was not found.
```

How do I fix this?

**Comment by mgrauer** [comment]
I'll provide some context here first for you @jwodder .

We have the two different services, dandiarchive and dandi-publish, each has its own Docker-Compose. We had tried some work before in #71 to unify them, but it was going to be a large maintenance burden, and we are planning to drop the dandiarchive side of things before too long (on the order of months). Developers would either need to work on the publish side or the archive side natively, and have the other side come up in Docker Compose--though I realize in your case it would be needed to test the CLI to have data that flows from one side to the other.

You could build a unified Docker compose, but the two upstream Docker composes may continue to change, so you might face some bitrot battles trying to keep up your unified system with the two upstream systems. Alternatively, you can bring up both docker composes individually, and set up a network bridge locally to get them talking to each other.

For specific help here, we think this is because there are two packages with the name `dandi`, the dandi cli and the dandi-publish system that are conflicting in your virtualenv when trying to start celery. @brianhelba has said he would rename dandi-publish to dandi-archive at some point which would help.

I think there was a temporary fix someone suggested, but I can't remember the specifics now well enough to say. I'll try to track that down or someone feel free to comment.

**Comment by dchiquit** [comment]
The problem is caused by dandi-cli and dandi-publish being installed at the same time. Due to some tragic lack of coordination they both contain a package called `dandi`.
https://github.com/dandi/dandi-publish/pull/123 should resolve the problem for the long term, but if you want to keep working on it you should be able to do something like `pip uninstall dandi-cli` after installing `dandi-publish.
