### ISSUE TITLE
OK to archive or delete this repo?

### ISSUE THREAD

**Issue by mgrauer** [dandi/dandi-publish#158]
We've moved all of the development work over to the dandi/dandi-api repo. Is it ok to archive or delete this repo, or are there any services relying on this?

I especially want to know from @jwodder @yarikoptic so I don't cause them any nasty surprises.

**Comment by jwodder** [comment]
The Docker Compose setup currently used in testing dandi-cli uses images built from this repo — though (aside from connecting the Publish container to Girder) I don't think any code actually goes through the resulting containers.

**Comment by mgrauer** [comment]
@jwodder can you move the Docker Compose setup to the dandi-api repo instead? We have a dependency of this (the dandi-publish) repo that we are trying to delete/migrate, so I want to make sure things don't break here for you, and I'd like you to be on the solution we are moving forward with (dandi-publish).

It could be that nothing we do here will break your work, but I cannot tell from your response.

**Comment by jwodder** [comment]
dandi-cli currently has an open PR to switch its Docker Compose setup from dandi-publish to dandi-api: https://github.com/dandi/dandi-cli/pull/283.  If & when that PR is accepted, the only thing still using this repo that I am aware of will be a Docker Hub repository.

**Comment by yarikoptic** [comment]
docker hub AFAIK does no longer build docker images for us. I think it should be safe to archive this repository.  I will do that now: 
- I have added to all open issues `closed-before-archiving` label
- I have closed all but this issue (which I will close right now)
- I will archive this repo

@waxlamp I hope this is not interfering with any work you are doing, but since this repo didn't see updates in 2 years, I think it should be ok.
