### ISSUE TITLE
Include downloadable URL with Assets in Asset listing

### ISSUE THREAD

**Issue by mgrauer** [dandi/dandi-publish#37]
When listing assets, a field should be included (perhaps optionally) that allows for downloading the asset via a URL (which should be the API Asset Download endpoint).

This might generalize to a broader issue of how to include such additional fields with listing endpoints.

**Comment by AlmightyYakob** [comment]
After discussion with @brianhelba, this information is already present after fetching a dandiset anyway, because all that's needed is to use the `uuid` of the asset to construct the endpoint, and to append `/download` (this functionality can be shown in #53). Due to this, I don't see any reason to keep this issue open.
